version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"    # OTLP gRPC receiver
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  user-service:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - SERVICE_NAME=user-service
    depends_on:
      - jaeger

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - user-service