version: '3.8'

services:
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/users
      - PORT=3001
    depends_on:
      - mongodb

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/products
      - PORT=3002
    depends_on:
      - mongodb

  order-service:
    build: ./order-service
    ports:
      - "3003:3003"
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/orders
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - PORT=3003
    depends_on:
      - mongodb
      - rabbitmq

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - user-service
      - product-service
      - order-service

volumes:
  mongo_data: